DROP SEQUENCE CLASS_SEQ;
DROP TABLE CALSS;

CREATE SEQUENCE CLASS_SEQ;
CREATE TABLE CLASS(
	CLASS_NO NUMBER PRIMARY KEY,
	MEMBER_NO NUMBER NOT NULL,
	CLASS_MAX NUMBER NOT NULL,
	CLASS_STARTDATE DATE NOT NULL,
	CLASS_ENDDATE DATE NOT NULL,
	CLASS_NAME VARCHAR2(500) NOT NULL,
	FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER(MEMBER_NO)
);