DROP TABLE CSBOARD;
DROP SEQUENCE CSSEQ;

CREATE SEQUENCE CSSEQ;
CREATE TABLE CSBOARD(

	CSNO NUMBER PRIMARY KEY,
	CSCATEGORY VARCHAR2(500) NOT NULL,
	CSTITLE VARCHAR2(1000) NOT NULL,
	CSNAME VARCHAR2(500) NOT NULL,
	CSCONMENT VARCHAR2(2000),
	CSDATE DATE NOT NULL

);

INSERT INTO CSBOARD 
VALUES(CSSEQ.NEXTVAL, '학습문의','안녕하세요','염따','고등래퍼4 나옵니다',SYSDATE);


SELECT CSNO, CSCATEGORY, CSTITLE, CSNAME, CSCONMENT, CSDATE
FROM CSBOARD
ORDER BY CSNO DESC;