DROP SEQUENCE MEMBER_SEQ;
DROP TABLE MEMBER;

CREATE SEQUENCE MEMBER_SEQ;
CREATE TABLE MEMBER(
	MEMBER_NO NUMBER PRIMARY KEY,
	MEMBER_ID VARCHAR2(500) NOT NULL,
	MEMBER_PW VARCHAR2(500) NOT NULL,
	MEMBER_PWCHK VARCHAR2(500) NOT NULL,
	MEMBER_NAME VARCHAR2(500) NOT NULL,
	MEMBER_EMAIL VARCHAR2(100) NOT NULL,
	MEMBER_PHONE VARCHAR2(100) NOT NULL,
	MEMBER_POST NUMBER NOT NULL,
	MEMBER_ADDR1 VARCHAR2(200) NOT NULL,
	MEMBER_ADDR2 VARCHAR2(200) NOT NULL,
	MEMBER_BIRTH VARCHAR2(100) NOT NULL,
	MEMBER_IMGNAME VARCHAR2(500),
	MEMBER_IMGPATH VARCHAR2(1000),
	MEMBER_TYPE VARCHAR2(4) NOT NULL,
	MEMBER_WITHDRAWAL VARCHAR2(2) NOT NULL,
	MEMBER_SNS VARCHAR2(500),
	CONSTRAINT MEMBER_UN UNIQUE(MEMBER_ID, MEMBER_EMAIL),
	CONSTRAINT MEMBER_CK1 CHECK(MEMBER_TYPE IN('A','SN','SG','S','T')),
	CONSTRAINT MEMBER_CK2 CHECK(MEMBER_WITHDRAWAL IN('Y','N'))
);


INSERT INTO MEMBER
VALUES (MEMBER_SEQ.NEXTVAL, 'ADMIN', '1234', '1234', '관리자', 'BEAN@KH.COM', '010-1234-5678','00000',
'서울시 강남구 역삼동', '남도빌딩', '1900-04-04', '', '', 'A', 'N', '');

SELECT * FROM MEMBER ORDER BY MEMBER_NO;

DELETE FROM MEMBER
WHERE MEMBER_NO= 62 ;

SELECT * FROM MEMBER ORDER BY MEMBER_NO DESC;

INSERT INTO MEMBER
VALUES (MEMBER_SEQ.NEXTVAL, 'user', 'userPw', 'userPw', '테스터', 'BEAN@KH.COM', '010-1234-5678','00000',
'서울시 강남구 역삼동', '남도빌딩', '1900-04-04', '', '', 'A', 'N', '');

