DROP SEQUENCE PAYMENT_SEQ;
DROP TABLE PAYMENT;

CREATE SEQUENCE PAYMENT_SEQ;
CREATE TABLE PAYMENT(
	PAYMENT_NO NUMBER PRIMARY KEY,
	MEMBER_NO NUMBER NOT NULL,
	CLASS_NO NUMBER NOT NULL,
	PAYMENT_METHOD VARCHAR2(50) NOT NULL,
	PAYMENT_PRICE VARCHAR2(50) NOT NULL,
	PAYMENT_STATE VARCHAR2(2) NOT NULL,
	PAYMENT_DATE DATE NOT NULL,
	PAYMENT_IMPUID VARCHAR2(100) NOT NULL,
	PAYMENT_REFUND VARCHAR2(2) NOT NULL,
	CONSTRAINT PAYMENT_CK1 CHECK(PAYMENT_STATE IN('Y','N')),
	CONSTRAINT PAYMENT_CK2 CHECK(PAYMENT_REFUND IN('Y','N')),
	FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER(MEMBER_NO),
	FOREIGN KEY(CLASS_NO) REFERENCES CLASS(CLASS_NO)
);

SELECT * FROM PAYMENT;