DROP SEQUENCE QUESTIONBOARD_SEQ;
DROP TABLE QUESTIONBOARD;

CREATE SEQUENCE QUESTIONBOARD_SEQ;
CREATE TABLE QUESTIONBOARD(
	
	QUESTIONBOARD_NO NUMBER PRIMARY KEY, 
	MEMBER_NO NUMBER NOT NULL,
	QUESTIONBOARD_NAME VARCHAR2(500) NOT NULL,
	QUESTIONBOARD_TITLE VARCHAR2(500) NOT NULL,
	QUESTIONBOARD_CONTENT VARCHAR2(4000) NOT NULL,
	QUESTIONBOARD_DATE DATE NOT NULL,
	QUESTIONBOARD_READCOUNT NUMBER NOT NULL,
	QUESTIONBOARD_STEP NUMBER NOT NULL,
	QUESTIONBOARD_GROUPNO NUMBER NOT NULL,
	QUESTIONBOARD_REPLY VARCHAR2(4000),
	QUESTIONBOARD_REPLYDATE DATE,
	QUESTIONBOARD_DELFLAG VARCHAR2(2),
	QUESTIONBOARD_IMGNAME VARCHAR2(500),
	QUESTIONBOARD_IMGPATH VARCHAR2(1000),
	QUESTIONBOARD_OCR VARCHAR2(500),
	FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER(MEMBER_NO),
	CONSTRAINT DELFLAG_CK CHECK(QUESTIONBOARD_DELFLAG IN ('Y', 'N'))

);

-- TODO : OCR type BLOB or CLOB 로 처리할 것
SELECT * FROM QUESTIONBOARD;

INSERT INTO QUESTIONBOARD 
VALUES(QUESTIONBOARD_SEQ.NEXTVAL, 2 ,'zzarbttoo', 'title', 'content', SYSDATE, 0, 1, 1, 'reply', null, 'N', null, null, null);
